include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    require_trailing_commas: true
    use_super_parameters: true
